name: Create Github Release

on:
  push:
    tags:
      - '*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "$GITHUB_REF_NAME" --generate-notes
